name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Check Python version
        run: python3 -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: >
          sudo apt-get install -y
          flake8
          gettext
          gir1.2-glib-2.0
          gir1.2-gtk-3.0
          gir1.2-keybinder-3.0
          gir1.2-pango-1.0
          python3
          python3-dev
          python3-gi
          python3-pytest
          qalc
          xvfb
      - name: Run linter
        run: make check
      - name: Run unit tests
        run: xvfb-run py.test-3 .
      - name: Install
        run: |
          make PREFIX=/usr/local install
          make DESTDIR=pkg PREFIX=/usr install
          make clean
